$(document).ready(function(){
  $(".owl-carousel.owl-one").owlCarousel({
  	margin:10,
  	loop:true,
  	dots:false,
  	nav:true,
  	responsive:{
        0:{
            items:1
        },
        300:{
          items:2
        },
        773:{
            items:3
        },
        1000:{
            items:4
        }
    },
    autoplay:true
  });
  $(".owl-carousel.owl-two").owlCarousel({
  	margin:30,
  	loop:false,
  	dots:false,
  	nav:true,
  	responsive:{
        0:{
          items:1
        },
        400:{
            items:2
        },
        600:{
            items:3
        },
        820:{
          items:4
        },
        1000:{
            items:5
        }
    },
    autoplay:true
  });
  $(".owl-carousel.owl-sale").owlCarousel({
  	margin:30,
  	loop:true,
  	dots:false,
  	nav:true,
  	responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    },
    autoplay:true
  });
   $(".owl-carousel.owl-similar-products").owlCarousel({
  	margin:30,
  	loop:true,
  	dots:false,
  	nav:true,
  	responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    },
    autoplay:true
  });
  $(".owl-carousel.owl-list-img-detail").owlCarousel({
  	margin:10,
  	loop:false,
  	dots:false,
  	nav:false,
  	responsive:{
        0:{
            items:3
        },
        600:{
            items:4
        },
        1000:{
            items:5
        }
    },
    autoplay:true
  });
   
});